#!/usr/bin/env bash

current_dir=$(pwd)
echo "${currdir}"

protobuf_dependencies="
    protoc
"

# 
cita_node_intf_files="
    blockchain.proto
    snapshot.proto
"

cita_component_intf_files="
    auth.proto
    citacode.proto
    consensus.proto
    request.proto
    communication.proto
    executor.proto
    response.proto
    sync.proto
"

cita_grpc_intf_files="
    citacode.proto
    executor.proto
"

function check_dependencies {
    local l_dependencies="$1"
    for bin in ${l_dependencies}; do
        if [ ! -x "$(which ${bin})" ]; then
            echo -e "\033[31m[Error] Please check if you have installed \033[43m${bin}\033[0m in your \$PATH. \033[0m"
            echo "See dependense decription in README.md for more detail!"
            exit 1
        fi
    done
}

go_dependencies="
    ${protobuf_dependencies}
    protoc-gen-go
"

function gen_go {
    check_dependencies "${go_dependencies}"
    echo -e "Generate\033[33m go\033[0m files from protos:"
    
    # Support for go sdk, needs only cita_node_intf_files for now. 
    for protofile in ${cita_node_intf_files}; do
        rm -f ${protofile/%.proto/.go.pb}
        protoc --go_out=plugins=grpcserial:${current_dir}/go -Iprotos ${protofile}
        echo "  ${protofile} -> ${protofile/%.proto/.go.pb}"
    done

    echo -e "End generate go files, and results write to \$current_dir/go.\n"
}

js_dependencies="
    ${protobuf_dependencies}
"

function gen_js {
    check_dependencies "${js_dependencies}"
    echo -e "Generate\033[33m js\033[0m files from protos:"
    
    # Support for js sdk, needs only cita_node_intf_files for now.
    for protofile in ${cita_node_intf_files}; do
        rm -f ${protofile/%.proto/_pb.js}
        protoc --js_out=import_style=commonjs,binary:${current_dir}/js -Iprotos ${protofile}
        echo "  ${protofile} -> ${protofile/%.proto/_pb.js}"
    done

    echo -e "End generate js files, and results write to \$current_dir/js.\n"
}

java_dependencies="
    ${protobuf_dependencies}
"

function gen_java {
    check_dependencies "${java_dependencies}"
    echo -e "Generate\033[33m java\033[0m files from protos:"
    
    # Support for java sdk, needs only cita_node_intf_files for now.
    for protofile in ${cita_node_intf_files}; do
        rm -f ${protofile/%.proto/.java}
        protoc --java_out=${current_dir}/java -Iprotos ${protofile}
        echo "  ${protofile} -> ${protofile/%.proto/.java}"
    done

    echo -e "End generate java files, and results write to \$current_dir/java.\n"
}

python_dependencies="
    ${protobuf_dependencies}
"

function gen_python {
    check_dependencies "${python_dependencies}"
    echo -e "Generate\033[33m python\033[0m files from protos:"
    
    # Support for python sdk, needs only cita_node_intf_files for now.
    for protofile in ${cita_node_intf_files}; do
        rm -f ${protofile/%.proto/_pb2.py}
        protoc --python_out=${current_dir}/python -Iprotos ${protofile}
        echo "  ${protofile} -> ${protofile/%.proto/_pb2.py}"
    done

    echo -e "End generate python files, and results write to \$current_dir/python.\n"
}

rust_dependencies="
    ${protobuf_dependencies}
    protoc-gen-rust
    protoc-gen-rust-grpc
"

function gen_rust {
    check_dependencies "${rust_dependencies}"
    echo -e "Generate\033[33m rust\033[0m files from protos:"
    
    # Support for rust sdk, needs only cita_node_intf_files for now.
    for protofile in ${cita_node_intf_files}; do
        rm -f ${protofile/%.proto/.rs}
        protoc --rust_out=${current_dir}/rust -Iprotos ${protofile}
        echo "  ${protofile} -> ${protofile/%.proto/.rs}"
    done

    for protofile in ${cita_component_intf_files}; do
        rm -f ${protofile/%.proto/.rs}
        protoc --rust_out=${current_dir}/rust -Iprotos ${protofile}
        echo "  ${protofile} -> ${protofile/%.proto/.rs}"
    done

    # Generate grpc
    for protofile in ${cita_grpc_intf_files}; do
        rm -f ${protofile/%.proto/_grpc.rs}
        protoc --rust-grpc_out=${current_dir}/rust -Iprotos ${protofile}
        echo "  ${protofile} -> ${protofile/%.proto/_grpc.rs}"
    done

    # Need to prefix the codes generated by proto compiler
    cd rust
    ./prefix.sh
    cd ..

    echo -e "End generate rust files, and results write to \$current_dir/rust.\n"
}

function main {
    gen_go
    gen_js
    gen_java
    gen_python
    gen_rust
}

main

