// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snapshot.proto

public final class Snapshot {
  private Snapshot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Cmd}
   */
  public enum Cmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Begin = 0;</code>
     */
    Begin(0),
    /**
     * <code>Clear = 1;</code>
     */
    Clear(1),
    /**
     * <code>Snapshot = 2;</code>
     */
    Snapshot(2),
    /**
     * <code>Restore = 3;</code>
     */
    Restore(3),
    /**
     * <code>End = 4;</code>
     */
    End(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Begin = 0;</code>
     */
    public static final int Begin_VALUE = 0;
    /**
     * <code>Clear = 1;</code>
     */
    public static final int Clear_VALUE = 1;
    /**
     * <code>Snapshot = 2;</code>
     */
    public static final int Snapshot_VALUE = 2;
    /**
     * <code>Restore = 3;</code>
     */
    public static final int Restore_VALUE = 3;
    /**
     * <code>End = 4;</code>
     */
    public static final int End_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cmd valueOf(int value) {
      return forNumber(value);
    }

    public static Cmd forNumber(int value) {
      switch (value) {
        case 0: return Begin;
        case 1: return Clear;
        case 2: return Snapshot;
        case 3: return Restore;
        case 4: return End;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
            public Cmd findValueByNumber(int number) {
              return Cmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Snapshot.getDescriptor().getEnumTypes().get(0);
    }

    private static final Cmd[] VALUES = values();

    public static Cmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Cmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Cmd)
  }

  /**
   * Protobuf enum {@code Resp}
   */
  public enum Resp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BeginAck = 0;</code>
     */
    BeginAck(0),
    /**
     * <code>ClearAck = 1;</code>
     */
    ClearAck(1),
    /**
     * <code>SnapshotAck = 2;</code>
     */
    SnapshotAck(2),
    /**
     * <code>RestoreAck = 3;</code>
     */
    RestoreAck(3),
    /**
     * <code>EndAck = 4;</code>
     */
    EndAck(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BeginAck = 0;</code>
     */
    public static final int BeginAck_VALUE = 0;
    /**
     * <code>ClearAck = 1;</code>
     */
    public static final int ClearAck_VALUE = 1;
    /**
     * <code>SnapshotAck = 2;</code>
     */
    public static final int SnapshotAck_VALUE = 2;
    /**
     * <code>RestoreAck = 3;</code>
     */
    public static final int RestoreAck_VALUE = 3;
    /**
     * <code>EndAck = 4;</code>
     */
    public static final int EndAck_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Resp valueOf(int value) {
      return forNumber(value);
    }

    public static Resp forNumber(int value) {
      switch (value) {
        case 0: return BeginAck;
        case 1: return ClearAck;
        case 2: return SnapshotAck;
        case 3: return RestoreAck;
        case 4: return EndAck;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Resp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Resp> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Resp>() {
            public Resp findValueByNumber(int number) {
              return Resp.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Snapshot.getDescriptor().getEnumTypes().get(1);
    }

    private static final Resp[] VALUES = values();

    public static Resp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Resp(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Resp)
  }

  public interface SnapshotReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SnapshotReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Cmd cmd = 1;</code>
     */
    int getCmdValue();
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    Snapshot.Cmd getCmd();

    /**
     * <code>uint64 start_height = 2;</code>
     */
    long getStartHeight();

    /**
     * <code>uint64 end_height = 3;</code>
     */
    long getEndHeight();

    /**
     * <code>string file = 4;</code>
     */
    java.lang.String getFile();
    /**
     * <code>string file = 4;</code>
     */
    com.google.protobuf.ByteString
        getFileBytes();
  }
  /**
   * Protobuf type {@code SnapshotReq}
   */
  public  static final class SnapshotReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SnapshotReq)
      SnapshotReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SnapshotReq.newBuilder() to construct.
    private SnapshotReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SnapshotReq() {
      cmd_ = 0;
      startHeight_ = 0L;
      endHeight_ = 0L;
      file_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SnapshotReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 16: {

              startHeight_ = input.readUInt64();
              break;
            }
            case 24: {

              endHeight_ = input.readUInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              file_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Snapshot.internal_static_SnapshotReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Snapshot.internal_static_SnapshotReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Snapshot.SnapshotReq.class, Snapshot.SnapshotReq.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public Snapshot.Cmd getCmd() {
      Snapshot.Cmd result = Snapshot.Cmd.valueOf(cmd_);
      return result == null ? Snapshot.Cmd.UNRECOGNIZED : result;
    }

    public static final int START_HEIGHT_FIELD_NUMBER = 2;
    private long startHeight_;
    /**
     * <code>uint64 start_height = 2;</code>
     */
    public long getStartHeight() {
      return startHeight_;
    }

    public static final int END_HEIGHT_FIELD_NUMBER = 3;
    private long endHeight_;
    /**
     * <code>uint64 end_height = 3;</code>
     */
    public long getEndHeight() {
      return endHeight_;
    }

    public static final int FILE_FIELD_NUMBER = 4;
    private volatile java.lang.Object file_;
    /**
     * <code>string file = 4;</code>
     */
    public java.lang.String getFile() {
      java.lang.Object ref = file_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        file_ = s;
        return s;
      }
    }
    /**
     * <code>string file = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFileBytes() {
      java.lang.Object ref = file_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        file_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != Snapshot.Cmd.Begin.getNumber()) {
        output.writeEnum(1, cmd_);
      }
      if (startHeight_ != 0L) {
        output.writeUInt64(2, startHeight_);
      }
      if (endHeight_ != 0L) {
        output.writeUInt64(3, endHeight_);
      }
      if (!getFileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, file_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != Snapshot.Cmd.Begin.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      if (startHeight_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, startHeight_);
      }
      if (endHeight_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, endHeight_);
      }
      if (!getFileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, file_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Snapshot.SnapshotReq)) {
        return super.equals(obj);
      }
      Snapshot.SnapshotReq other = (Snapshot.SnapshotReq) obj;

      boolean result = true;
      result = result && cmd_ == other.cmd_;
      result = result && (getStartHeight()
          == other.getStartHeight());
      result = result && (getEndHeight()
          == other.getEndHeight());
      result = result && getFile()
          .equals(other.getFile());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + START_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartHeight());
      hash = (37 * hash) + END_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndHeight());
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFile().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Snapshot.SnapshotReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Snapshot.SnapshotReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Snapshot.SnapshotReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Snapshot.SnapshotReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Snapshot.SnapshotReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Snapshot.SnapshotReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Snapshot.SnapshotReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Snapshot.SnapshotReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Snapshot.SnapshotReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Snapshot.SnapshotReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Snapshot.SnapshotReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Snapshot.SnapshotReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Snapshot.SnapshotReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SnapshotReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SnapshotReq)
        Snapshot.SnapshotReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Snapshot.internal_static_SnapshotReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Snapshot.internal_static_SnapshotReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Snapshot.SnapshotReq.class, Snapshot.SnapshotReq.Builder.class);
      }

      // Construct using Snapshot.SnapshotReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        startHeight_ = 0L;

        endHeight_ = 0L;

        file_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Snapshot.internal_static_SnapshotReq_descriptor;
      }

      public Snapshot.SnapshotReq getDefaultInstanceForType() {
        return Snapshot.SnapshotReq.getDefaultInstance();
      }

      public Snapshot.SnapshotReq build() {
        Snapshot.SnapshotReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Snapshot.SnapshotReq buildPartial() {
        Snapshot.SnapshotReq result = new Snapshot.SnapshotReq(this);
        result.cmd_ = cmd_;
        result.startHeight_ = startHeight_;
        result.endHeight_ = endHeight_;
        result.file_ = file_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Snapshot.SnapshotReq) {
          return mergeFrom((Snapshot.SnapshotReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Snapshot.SnapshotReq other) {
        if (other == Snapshot.SnapshotReq.getDefaultInstance()) return this;
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (other.getStartHeight() != 0L) {
          setStartHeight(other.getStartHeight());
        }
        if (other.getEndHeight() != 0L) {
          setEndHeight(other.getEndHeight());
        }
        if (!other.getFile().isEmpty()) {
          file_ = other.file_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Snapshot.SnapshotReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Snapshot.SnapshotReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Snapshot.Cmd getCmd() {
        Snapshot.Cmd result = Snapshot.Cmd.valueOf(cmd_);
        return result == null ? Snapshot.Cmd.UNRECOGNIZED : result;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmd(Snapshot.Cmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private long startHeight_ ;
      /**
       * <code>uint64 start_height = 2;</code>
       */
      public long getStartHeight() {
        return startHeight_;
      }
      /**
       * <code>uint64 start_height = 2;</code>
       */
      public Builder setStartHeight(long value) {
        
        startHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 start_height = 2;</code>
       */
      public Builder clearStartHeight() {
        
        startHeight_ = 0L;
        onChanged();
        return this;
      }

      private long endHeight_ ;
      /**
       * <code>uint64 end_height = 3;</code>
       */
      public long getEndHeight() {
        return endHeight_;
      }
      /**
       * <code>uint64 end_height = 3;</code>
       */
      public Builder setEndHeight(long value) {
        
        endHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 end_height = 3;</code>
       */
      public Builder clearEndHeight() {
        
        endHeight_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object file_ = "";
      /**
       * <code>string file = 4;</code>
       */
      public java.lang.String getFile() {
        java.lang.Object ref = file_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          file_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string file = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFileBytes() {
        java.lang.Object ref = file_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          file_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file = 4;</code>
       */
      public Builder setFile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        file_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file = 4;</code>
       */
      public Builder clearFile() {
        
        file_ = getDefaultInstance().getFile();
        onChanged();
        return this;
      }
      /**
       * <code>string file = 4;</code>
       */
      public Builder setFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        file_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SnapshotReq)
    }

    // @@protoc_insertion_point(class_scope:SnapshotReq)
    private static final Snapshot.SnapshotReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Snapshot.SnapshotReq();
    }

    public static Snapshot.SnapshotReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SnapshotReq>
        PARSER = new com.google.protobuf.AbstractParser<SnapshotReq>() {
      public SnapshotReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnapshotReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SnapshotReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SnapshotReq> getParserForType() {
      return PARSER;
    }

    public Snapshot.SnapshotReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SnapshotRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SnapshotResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Resp resp = 1;</code>
     */
    int getRespValue();
    /**
     * <code>.Resp resp = 1;</code>
     */
    Snapshot.Resp getResp();
  }
  /**
   * Protobuf type {@code SnapshotResp}
   */
  public  static final class SnapshotResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SnapshotResp)
      SnapshotRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SnapshotResp.newBuilder() to construct.
    private SnapshotResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SnapshotResp() {
      resp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SnapshotResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              resp_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Snapshot.internal_static_SnapshotResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Snapshot.internal_static_SnapshotResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Snapshot.SnapshotResp.class, Snapshot.SnapshotResp.Builder.class);
    }

    public static final int RESP_FIELD_NUMBER = 1;
    private int resp_;
    /**
     * <code>.Resp resp = 1;</code>
     */
    public int getRespValue() {
      return resp_;
    }
    /**
     * <code>.Resp resp = 1;</code>
     */
    public Snapshot.Resp getResp() {
      Snapshot.Resp result = Snapshot.Resp.valueOf(resp_);
      return result == null ? Snapshot.Resp.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resp_ != Snapshot.Resp.BeginAck.getNumber()) {
        output.writeEnum(1, resp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resp_ != Snapshot.Resp.BeginAck.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Snapshot.SnapshotResp)) {
        return super.equals(obj);
      }
      Snapshot.SnapshotResp other = (Snapshot.SnapshotResp) obj;

      boolean result = true;
      result = result && resp_ == other.resp_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESP_FIELD_NUMBER;
      hash = (53 * hash) + resp_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Snapshot.SnapshotResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Snapshot.SnapshotResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Snapshot.SnapshotResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Snapshot.SnapshotResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Snapshot.SnapshotResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Snapshot.SnapshotResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Snapshot.SnapshotResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Snapshot.SnapshotResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Snapshot.SnapshotResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Snapshot.SnapshotResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Snapshot.SnapshotResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Snapshot.SnapshotResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Snapshot.SnapshotResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SnapshotResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SnapshotResp)
        Snapshot.SnapshotRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Snapshot.internal_static_SnapshotResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Snapshot.internal_static_SnapshotResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Snapshot.SnapshotResp.class, Snapshot.SnapshotResp.Builder.class);
      }

      // Construct using Snapshot.SnapshotResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resp_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Snapshot.internal_static_SnapshotResp_descriptor;
      }

      public Snapshot.SnapshotResp getDefaultInstanceForType() {
        return Snapshot.SnapshotResp.getDefaultInstance();
      }

      public Snapshot.SnapshotResp build() {
        Snapshot.SnapshotResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Snapshot.SnapshotResp buildPartial() {
        Snapshot.SnapshotResp result = new Snapshot.SnapshotResp(this);
        result.resp_ = resp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Snapshot.SnapshotResp) {
          return mergeFrom((Snapshot.SnapshotResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Snapshot.SnapshotResp other) {
        if (other == Snapshot.SnapshotResp.getDefaultInstance()) return this;
        if (other.resp_ != 0) {
          setRespValue(other.getRespValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Snapshot.SnapshotResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Snapshot.SnapshotResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int resp_ = 0;
      /**
       * <code>.Resp resp = 1;</code>
       */
      public int getRespValue() {
        return resp_;
      }
      /**
       * <code>.Resp resp = 1;</code>
       */
      public Builder setRespValue(int value) {
        resp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Resp resp = 1;</code>
       */
      public Snapshot.Resp getResp() {
        Snapshot.Resp result = Snapshot.Resp.valueOf(resp_);
        return result == null ? Snapshot.Resp.UNRECOGNIZED : result;
      }
      /**
       * <code>.Resp resp = 1;</code>
       */
      public Builder setResp(Snapshot.Resp value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        resp_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Resp resp = 1;</code>
       */
      public Builder clearResp() {
        
        resp_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SnapshotResp)
    }

    // @@protoc_insertion_point(class_scope:SnapshotResp)
    private static final Snapshot.SnapshotResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Snapshot.SnapshotResp();
    }

    public static Snapshot.SnapshotResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SnapshotResp>
        PARSER = new com.google.protobuf.AbstractParser<SnapshotResp>() {
      public SnapshotResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnapshotResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SnapshotResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SnapshotResp> getParserForType() {
      return PARSER;
    }

    public Snapshot.SnapshotResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SnapshotReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SnapshotReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SnapshotResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SnapshotResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016snapshot.proto\"X\n\013SnapshotReq\022\021\n\003cmd\030\001" +
      " \001(\0162\004.Cmd\022\024\n\014start_height\030\002 \001(\004\022\022\n\nend_" +
      "height\030\003 \001(\004\022\014\n\004file\030\004 \001(\t\"#\n\014SnapshotRe" +
      "sp\022\023\n\004resp\030\001 \001(\0162\005.Resp*?\n\003Cmd\022\t\n\005Begin\020" +
      "\000\022\t\n\005Clear\020\001\022\014\n\010Snapshot\020\002\022\013\n\007Restore\020\003\022" +
      "\007\n\003End\020\004*O\n\004Resp\022\014\n\010BeginAck\020\000\022\014\n\010ClearA" +
      "ck\020\001\022\017\n\013SnapshotAck\020\002\022\016\n\nRestoreAck\020\003\022\n\n" +
      "\006EndAck\020\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SnapshotReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SnapshotReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SnapshotReq_descriptor,
        new java.lang.String[] { "Cmd", "StartHeight", "EndHeight", "File", });
    internal_static_SnapshotResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SnapshotResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SnapshotResp_descriptor,
        new java.lang.String[] { "Resp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
