// Code generated by protoc-gen-go.
// source: snapshot.proto
// DO NOT EDIT!

/*
Package snapshot is a generated protocol buffer package.

It is generated from these files:
	snapshot.proto

It has these top-level messages:
	SnapshotReq
	SnapshotResp
*/
package snapshot

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Cmd int32

const (
	Cmd_Begin    Cmd = 0
	Cmd_Clear    Cmd = 1
	Cmd_Snapshot Cmd = 2
	Cmd_Restore  Cmd = 3
	Cmd_End      Cmd = 4
)

var Cmd_name = map[int32]string{
	0: "Begin",
	1: "Clear",
	2: "Snapshot",
	3: "Restore",
	4: "End",
}
var Cmd_value = map[string]int32{
	"Begin":    0,
	"Clear":    1,
	"Snapshot": 2,
	"Restore":  3,
	"End":      4,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}

type Resp int32

const (
	Resp_BeginAck    Resp = 0
	Resp_ClearAck    Resp = 1
	Resp_SnapshotAck Resp = 2
	Resp_RestoreAck  Resp = 3
	Resp_EndAck      Resp = 4
)

var Resp_name = map[int32]string{
	0: "BeginAck",
	1: "ClearAck",
	2: "SnapshotAck",
	3: "RestoreAck",
	4: "EndAck",
}
var Resp_value = map[string]int32{
	"BeginAck":    0,
	"ClearAck":    1,
	"SnapshotAck": 2,
	"RestoreAck":  3,
	"EndAck":      4,
}

func (x Resp) String() string {
	return proto.EnumName(Resp_name, int32(x))
}

type SnapshotReq struct {
	Cmd         Cmd    `protobuf:"varint,1,opt,name=cmd,enum=Cmd" json:"cmd,omitempty"`
	StartHeight uint64 `protobuf:"varint,2,opt,name=start_height" json:"start_height,omitempty"`
	EndHeight   uint64 `protobuf:"varint,3,opt,name=end_height" json:"end_height,omitempty"`
	File        string `protobuf:"bytes,4,opt,name=file" json:"file,omitempty"`
}

func (m *SnapshotReq) Reset()         { *m = SnapshotReq{} }
func (m *SnapshotReq) String() string { return proto.CompactTextString(m) }
func (*SnapshotReq) ProtoMessage()    {}

type SnapshotResp struct {
	Resp Resp `protobuf:"varint,1,opt,name=resp,enum=Resp" json:"resp,omitempty"`
}

func (m *SnapshotResp) Reset()         { *m = SnapshotResp{} }
func (m *SnapshotResp) String() string { return proto.CompactTextString(m) }
func (*SnapshotResp) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("Cmd", Cmd_name, Cmd_value)
	proto.RegisterEnum("Resp", Resp_name, Resp_value)
}
